### ISSUE TITLE
eBPF For Windows Demo - Connection Tracking fails

### ISSUE THREAD

**Issue by dahavey** [microsoft/ebpf-for-windows-demo#53]
reference page: https://github.com/microsoft/ebpf-for-windows-demo/blob/main/connection_tracker/README.md

Running: cd out && powershell -NonInteractive -ExecutionPolicy Unrestricted %EBPF_ROOT%\bin\Convert-BpfToNative.ps1 -ProgramName conn_track.o

Fails with: Project "C:\Users\User\repos\ebpf-for-windows-demo\connection_tracker\bpf\out\conn_track.vcxproj" on
node 1 (default targets).
C:\Users\User\repos\ebpf-for-windows-demo\connection_tracker\bpf\out\conn_track.vcxproj(1,2134): erro
r MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBui
ld\Microsoft\VC\v170\Microsoft.Cpp.Default.props" was not found. Confirm that the expression in the I
mport declaration "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\V
C\v170\\Microsoft.Cpp.Default.props" is correct, and that the file exists on disk.
Done Building Project "C:\Users\User\repos\ebpf-for-windows-demo\connection_tracker\bpf\out\conn_trac
k.vcxproj" (default targets) -- FAILED.

The path: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\V
C\v170\\Microsoft.Cpp.Default.props
does not exist.

Also, I searched for Microsoft.Cpp.Default.props
which also does not exist on the disk.

How to proceed?

**Comment by gtrevi** [comment]
@dahavey 
I could not repro the failure following all the steps from scratch, although, the `README.md` has an error on setting up the `EBPF_ROOT` variable (step #2 of [Native eBPF program generation](https://github.com/microsoft/ebpf-for-windows-demo/blob/main/connection_tracker/README.md#native-ebpf-program-generation)). From the current repo's folder structure, it should be:

`set EBPF_ROOT=<your workspace path>\ebpf-for-windows-demo\packages\eBPF-for-Windows.0.5.0\build\native`

instead of:

`set EBPF_ROOT=c:\ebpf-for-windows-demo\packages\eBPF-for-Windows.0.1.4\build\native`

**Comment by dahavey** [comment]
Copied ebpf-printk.guid into current directory and got:
C:\Users\User\repos\ebpf-for-windows-demo\x64\Release>.\conn_tracker.exe
Press Ctrl-C to shutdown
bpf_object__load for conn_track.sys failed: 131

**Comment by shpalani** [comment]
Tested after the fix of #18, conn_tracker.exe works.

PS C:\ebpf-for-windows-demo\Debug> .\conn_tracker.exe
Press Ctrl-C to shutdown

**Comment by shpalani** [comment]
@dahavey : Can you please verify and close?
